I took these labs from An Introduction to Statistical Learning with Applications in Python (ISLP) Chapter 2.
Copyright belong to ISLP authors!
Checkout at https://www.statlearning.com for more information

A package is a collection of modules that are not necessarily included in the base Python distribution. The name **numpy** is abbreviation for _numerical Python_. To access **numpy** we must first **import** it

In [7]:
x = [3, 4, 5]
y = [1, 2, 3]
x+y

[3, 4, 5, 1, 2, 3]

In [3]:
import numpy as np

In the previous line, we named numpy as module np; an abbreviation for easier referencing. We use the _np.array()_ to define x and y, which are one-dimensional arrays, i.e. vectors.

In [4]:
x = np.array([3, 4, 5])
y = np.array([1, 2, 3])

Since x and y have been defined using np.array(), we get a sensible result when we add them together. It is completely differ from define x and y without using numpy

In [5]:
x+y

array([4, 6, 8])

In numpy, matrices are typically represented as two-dimensional arrays, and vectors as one-dimensional arrays. We can create two-dimensional arrays as follows:

In [9]:
z = np.array([[1, 2], [3, 4], [34,2]])
z

array([[ 1,  2],
       [ 3,  4],
       [34,  2]])

The object z has several _attributes_, or _associated object_. To access an attribute of z, we type _z.attribute_ where we replace _attribute_ with the name of the attribute. For instance, we can access the _ndim_ attribute of z as follows.

In [11]:
z.ndim

2

The output indicates that z is a two-dimensional array. Similarly, _z.dtype_ is the datatype attribute of the object z. This indicates that z comprises 64-bit integers:

In [12]:
z.dtype

dtype('int64')

Why is z comprised in integer? This is because we created z by passing in exclusively integers to the np.array() function. If we had passed in any decimals, then we would have obtained any array of floating point numbers (i.e. real-valued numbers)

In [25]:
np.array([[1, 2],[3.0, 4]]).dtype

dtype('float64')

The array z is two-dimensional. We can find out the numbers of rows and columns by looking at its _shape_ attribute.

In [35]:
z.shape

(3, 2)

Summarize here.
We knew attributes such: **ndim, shape, dtype** and
        functions such: **print(), np.array()**

What is a method? A method is a function that associate with an object. For instance, given an array x, the expression of _x.sum()_ sums all of its elements, using the **sum()** method for arrays. The call **x.sum()** automatically provides x as the first argument to its **sum()** method.

In [61]:
x = np.array([1,2.2,3,4])
x.sum()

np.float64(10.2)

We could also sum the elements of x by passing in x as an argument to the **np.sum()** function.

In [63]:
x = np.array([1,2.2,3,4])
np.sum(x)

np.float64(10.2)

As another example, the **reshape()** method return a new array with the same elements of x, but a difference shape. We do this by passing in a **tuple** in our call to **reshape()**, in this case **(2, 3)**. This tuple specifies that we would like to create a two-dimensional array with 2 rows and 3 columns.

Like lists, tuples represent a sequence of objects. Why do we need more than one way to create a sequence? There are a few differences between tuples and lists, but perhaps the most important is that elements of a tuple **cannot** be modified, whereas elements of a list can be.

In [75]:
x = np.array([1,2,6,3,4,7])
print("beginning x:\n", x)
x_reshape = x.reshape(2, 3)
print("reshaped x:\n", x_reshape)

beginning x:
 [1 2 6 3 4 7]
reshaped x:
 [[1 2 6]
 [3 4 7]]


The previous outputs reveals that numpy arrays are specified as a sequence of rows. This is called row-major ordering, as opposed to column-major ordering. Python (and hence numpy) uses 0-based indexing. This means that to access the top left element of **x_reshape**, we type in **x_reshape[0,0]**

In [84]:
x_reshape[0, 0]

np.int64(1)

Similarly, x_reshape[1,2] yields the element in the second row and the third column of _x_reshape_

In [85]:
x_reshape[1,2]

np.int64(7)

Similarly, x[2] yields the third entry of x. Now, let's modify the top left element of x_reshape. To our surprise, we discover that the first element of x has been modified as well!

In [89]:
print('x before we modify x_reshape:\n',x)
print('x_reshape before we modify x_reshape:\n',x_reshape)
x_reshape[0,0] = 5
print('x_reshape after we modify its top left element:\n',x_reshape)
print('x after we modify top left element of x_reshape:\n',x)

x before we modify x_reshape:
 [1 2 6 3 4 7]
x_reshape before we modify x_reshape:
 [[1 2 6]
 [3 4 7]]
x_reshape after we modify its top left element:
 [[5 2 6]
 [3 4 7]]
x after we modify top left element of x_reshape:
 [5 2 6 3 4 7]


Modifying x_reshape also modified x because the two objects occupy the same space in memory. We just saw that we can modify an element of an array. Can we also modify a tuple? It turns out that we **cannot** - and trying to do so introduces an _exception_, or error.

In [90]:
my_tuple = (1, 2, 3)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [91]:
my_list = [1, 2, 3]
my_list[0] = -1
my_list

[-1, 2, 3]

We now briefly mention some attributes of arrays that will come in handy. An array's _shape_ attribute contains its dimension; this is always a tuple. The _ndim_ attribute yields the number of dimensions, and _T_ provides its transpose.

In [139]:
print('x_reshape:\n',x_reshape)
print('x_reshape shape:\n',x_reshape.shape)
print('x_reshape dimensions:\n',x_reshape.ndim)
print('x_reshape transpose:\n',x_reshape.T)

x_reshape:
 [[5 2 6]
 [3 4 7]]
x_reshape shape:
 (2, 3)
x_reshape dimensions:
 2
x_reshape transpose:
 [[5 3]
 [2 4]
 [6 7]]


Notice that the three individual outputs **(2,3); 2; and array [[5 3] [2 4] [6 7]]** are themselves output as a tuple. We will often want to apply functions to arrays. For instance, we can compute the square root of the entries using the **np.sqrt()** function:

In [136]:
print(np.sqrt(x_reshape))

[[2.23606798 1.41421356 2.44948974]
 [1.73205081 2.         2.64575131]]


We can also square the elements

In [135]:
np.square(x_reshape)

array([[25,  4, 36],
       [ 9, 16, 49]])

We will often want to generate random data. The **np.random.normal()** function generates a vector of random normal variables. We can learn more about this function by looking at the help page, via a call to **np.random.normal?**. The first line of the help page reads **normal(loc=0.0, scale=1.0, size=None)**. This _signature_ line tells us that the function's arguments are **loc, scale, and size**. These are keyword arguments, which mean that when they are passed into the function, they can be referred to by name (in any order). By default, this function will generate random normal variable(s), with mean (**loc**) 0 and standard deviation (**scale**) 1, furthermore, a single random variables will be generated unless the argument to **size** is changed. We now generate 50 independent random variables from _N(0,1)_ distribution.

In [145]:
x = np.random.normal(size=50)
x

array([-0.51373708,  0.2237079 , -1.60538803,  1.24576631,  0.50719747,
       -1.52855992,  0.51670836, -0.08775729, -0.27822085, -0.22940754,
        1.19605511, -1.2741447 , -0.44031242, -0.05034378,  0.4217309 ,
       -0.71517286, -1.95379767,  0.51549111,  0.51057012,  0.11901565,
        0.52920898,  1.41146532, -1.55047268,  0.7458456 , -0.88516129,
        0.88603645,  1.25188542,  1.87837796,  0.97968345, -0.08111544,
       -0.46263811, -2.03703137, -0.32963767,  0.61611915, -0.07599431,
        1.03154232,  2.61829193, -0.39185805,  2.57382413,  1.47007108,
        2.85303969, -0.83211448, -0.60859715, -0.49563845, -0.53483686,
       -0.15633561,  0.96531911,  1.46292226,  0.38762212,  0.47909112])

We create an array _y_ by adding an independent _N(50,1)_ random variables to each element of _x_

In [146]:
y = x + np.random.normal(loc=50, scale=1, size=50)

The **np.corrcoef()** function computes the _correlation matrix_ between x and y. The off-diagonal elements give the correlation between x and y

In [147]:
np.corrcoef(x,y)

array([[1.       , 0.7578942],
       [0.7578942, 1.       ]])

We can use np.mean(), np.var(), and np.std() function to compute mean, variance, and standard deviation of arrays. These functions are also available as methods on the arrays.

In [150]:
x = np.array([[2,3],[4,5],[6,7],[8,9]])
x

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [164]:
np.mean(x), x.mean()

(np.float64(5.5), np.float64(5.5))

In [158]:
np.var(x), x.var(), np.mean((x-x.mean())**2)

(np.float64(5.25), np.float64(5.25), np.float64(5.25))

In [160]:
np.std(x), x.std(), np.sqrt(np.var(x))

(np.float64(2.29128784747792),
 np.float64(2.29128784747792),
 np.float64(2.29128784747792))

The np.mean(), np.var(), and np.std() can also be applied to the rows and columns of a matrix. To see this, we construct a 10x3 matrix of N(0,1) random variables, and consider computing its row sums.

In [173]:
rng = np.random.default_rng(3)

In [180]:
X = rng.standard_normal((10,3))
X

array([[-0.88645994, -0.29172023,  0.88253897],
       [ 0.58035002,  0.0915167 ,  0.67010435],
       [-2.82816231,  1.02130682, -0.95964476],
       [-1.66861984,  0.27644576,  0.70054489],
       [-0.44476746, -1.07640584,  0.02612483],
       [-0.05274731,  1.40559817,  0.74740799],
       [ 0.19381565,  1.11163321, -0.20552305],
       [-0.92589957,  0.58405831,  0.58253842],
       [-0.21482891, -0.78280858,  0.22915391],
       [-2.49389428,  0.69012477,  0.49136826]])

In [236]:
X.mean(), X.std()

(np.float64(-0.08489503571956641), np.float64(0.9989659565265708))

Since arrays are row-major ordered, the first axis aka first col, i.e. axis=0, refers to its rows. We pass this argument into the mean() method for object x.

In [237]:
X.mean(axis=0)

array([-0.8741214 ,  0.30297491,  0.31646138])

The following yields the same result.

In [238]:
X.mean(0)

array([-0.8741214 ,  0.30297491,  0.31646138])